routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HouseController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', [HouseController::class, 'index']);
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('houses', HouseController::class);
Route::resource('houses.reviews', ReviewController::class)->shallow();

app/Models/House.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class House extends Model
{
    use HasFactory;

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

app/Models/Review.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'house_id',
        'landlordRating',
        'houseCondition',
        'overallExperience',
        'bestAndWorstThing',
        'comment'
    ];

    public function house()
    {
        return $this->belongsTo(House::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/HouseController.php
<?php

namespace App\Http\Controllers;

use App\Models\House;
use Illuminate\Http\Request;

class HouseController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $houses = House::all();
        return view('houses.index', compact('houses'));
        //
    }
}

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Models\Review;
use App\Models\House;
use Illuminate\Http\Request;
use DB;

class ReviewController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($houseId)
    {
        $house = House::find($houseId);
        $reviews = $house->reviews;

        return view('reviews.index', compact('reviews', 'houseId'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($houseId)
    {
        $user = auth()->user();
        $review = DB::table('reviews')->where('house_id', $houseId)->where('user_id', $user->id)->get();
        if ($review->count() == 1)
          return back()->with('error', 'You are not able to review same property more than once!');
        if ($user->reviews->count() == 3)
          return back()->with('error', 'You are not able to review more than 3 properties!');
        return view('reviews.create', compact('houseId'));
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($houseId, Request $request)
    {
        $user = auth()->user();
        $house = House::find($houseId);
        $house->reviews()->create($request->all() + ['user_id'=> $user->id]);
        return redirect()->route('houses.reviews.index', $houseId);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/houses/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    @if(session()->has('error'))
        <div class="alert alert-danger col-md-8">
            {{ session()->get('error') }}
        </div>
    @endif
    @foreach($houses as $house)
        <div class="row mb-3">
            <div class="col-md-8">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row text-center ">
                            <div class="col-md-8">
                                <h5>{{$house->title}}, {{$house->address}}, {{$house->postCode}}</h5>
                                <p>{{$house->description}}</p>
                                <p>
                                    <i class="fa fa-bed"> x{{$house->bedrooms}}</i>
                                    <i class="icon-bath fa fa-bath"> x{{$house->bathrooms}}</i>
                                </p>
                                <div> Call: {{$house->contactNumber}}</div>
                            </div>
                            <div class="col-md-4">
                                <h3>£{{$house->price}} pcm</h3>
                                <small>An estimated Price*</small>
                                <div class="sub-row">
                                    <a href="{{route('houses.reviews.index', [$house->id])}}" class="btn btn-success btn-sm btn-block">View Reviews</a>
                                    <a href="{{route('houses.reviews.create', [$house->id])}}" class="btn btn-primary btn-sm btn-block">Add Review</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/reviews/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif
    <h3>Please review the house</h3><br>
    <form method="post" action="{{route('houses.reviews.store', [$houseId])}}">
        {{csrf_field()}}
        <div class="form-group">
            <label for="houseCondition">How would you rate the overall condition of the house? </label><br>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="houseCondition" id="inlineRadio1" value="1">
                <label class="form-check-label" for="inlineRadio1">1</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="houseCondition" id="inlineRadio2" value="2">
                <label class="form-check-label" for="inlineRadio2">2</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="houseCondition" id="inlineRadio3" value="3">
                <label class="form-check-label" for="inlineRadio3">3</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="houseCondition" id="inlineRadio4" value="4">
                <label class="form-check-label" for="inlineRadio4">4</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="houseCondition" id="inlineRadio5" value="5">
                <label class="form-check-label" for="inlineRadio5">5</label>
            </div>
        </div>

        <div class="form-group">
            <label for="landlordRating">What's the landlord like? </label><br>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="landlordRating" id="inlineRadio1" value="1">
                <label class="form-check-label" for="inlineRadio1">1</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="landlordRating" id="inlineRadio2" value="2">
                <label class="form-check-label" for="inlineRadio2">2</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="landlordRating" id="inlineRadio3" value="3">
                <label class="form-check-label" for="inlineRadio3">3</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="landlordRating" id="inlineRadio4" value="4">
                <label class="form-check-label" for="inlineRadio4">4</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="landlordRating" id="inlineRadio5" value="5">
                <label class="form-check-label" for="inlineRadio5">5</label>
            </div>
        </div>

        <div class="form-group">
            <label for="overallExperience">How was your overall experience? </label><br>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="overallExperience" id="inlineRadio1" value="1">
                <label class="form-check-label" for="inlineRadio1">1</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="overallExperience" id="inlineRadio2" value="2">
                <label class="form-check-label" for="inlineRadio2">2</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="overallExperience" id="inlineRadio3" value="3">
                <label class="form-check-label" for="inlineRadio3">3</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="overallExperience" id="inlineRadio4" value="4">
                <label class="form-check-label" for="inlineRadio4">4</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="overallExperience" id="inlineRadio5" value="5">
                <label class="form-check-label" for="inlineRadio5">5</label>
            </div>
        </div>

        <div class="form-group">
            <label for="exampleFormControlTextarea1">What's the best & worst thing about the house?</label>
            <textarea name="bestAndWorstThing" class="form-control" id="exampleFormControlTextarea1" rows="2"></textarea>
        </div>

        <div class="form-group">
            <label for="exampleFormControlTextarea1">Any Additional comments you want to say?</label>
            <textarea name="comment" class="form-control" id="exampleFormControlTextarea2" rows="2"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
        <a href="{{route('houses.index')}}" class="btn btn-danger">Back</a>
    </form>

</div>
  @endsection

resources/views/reviews/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h3>House #{{ $houseId }} Reviews</h3><br>
        @if($reviews->count() == 0)
            <div>No Reviews Posted for this House yet</div>
        @endif
        @foreach ($reviews as $review)
            <div class="one-review">
                <div class="row">
                    <div class="col-md-6">
                        <p class="font-weight-bold">{{$review->user->name}}</p>
                    </div>
                    <div class="col-md-6">
                        Posted On:
                        {{date('d-m-Y', strtotime($review->created_at))}}
                    </div>
                </div>
                <div class="row text-success">
                    <div class="col-md-12">
                        <span class="text-rating">Landlord Rating:</span>
                        @for ($i = 0; $i < $review->landlordRating; $i++)
                          <i class="fa fa-star"></i>
                        @endfor
                    </div>
                </div>
                <div class="row text-success">
                    <div class="col-md-12">
                        <span class="text-rating">House Condition:</span>
                        @for ($i = 0; $i < $review->houseCondition; $i++)
                          <i class="fa fa-star"></i>
                        @endfor
                    </div>
                </div>
                <div class="row text-success">
                    <div class="col-md-12">
                        <span class="text-rating">Overall Experience:</span>
                        @for ($i = 0; $i < $review->overallExperience; $i++)
                          <i class="fa fa-star"></i>
                        @endfor
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-md-12">
                        <h6>{{$review->bestAndWorstThing}}</h6>
                        <p>{{$review->comment}}</p>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-md-8">
                        <button type="button" class="btn btn-primary"><i class="fa fa-share-alt"></i> Share</button>

                    </div>
                    <div class="col-md-4">
                        <ul class="list-inline list-unstyled">
                            <li class="list-inline-item">
                                <p>is this helpful to you?</p>
                            </li>
                            <li class="list-inline-item"><button type="button" class="btn btn-outline-success">Yes</button>
                            </li>
                            <li class="list-inline-item"><button type="button" class="btn btn-outline-danger">No</button>
                            </li>
                        </ul>





                    </div>
                </div>
            </div>
            <hr>
        @endforeach
    </div>
@endsection